name: "Notify Chrome Version Update"

on:
  workflow_call:
    inputs:
      version:
        description: "最新的 Chrome 版本號"
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        run: echo "Chrome 已更新到版本 ${{ inputs.version }}！"
